CREATE TABLE RECIPE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20),
    CUISINE VARCHAR(20),
    DESCRIPTION VARCHAR(255),
    SERVING_SIZE INT(10) unsigned,
    IMAGE VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE INGREDIENT(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    QUANTITY INT(10) unsigned,
    MEASUREMENT VARCHAR(100),
    RECIPE_ID BIGINT,
    PRIMARY KEY (ID),
    foreign key (RECIPE_ID) references RECIPE(ID)
);

CREATE TABLE PROCESS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    Step INT(50) unsigned,
    RECIPE_ID BIGINT,
    PRIMARY KEY (ID),
    foreign key (RECIPE_ID) references RECIPE(ID)
);

CREATE TABLE MENU(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SOURCE VARCHAR(20),
    RECIPE_ID BIGINT,
    PRIMARY KEY (ID)
);